# Generated by Django 5.1 on 2024-08-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Blood_Type', models.CharField(max_length=20)),
                ('Medeical_Condition', models.CharField(max_length=100)),
                ('Date_Of_Admission', models.DateField()),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
                ('Insurance_Provider', models.CharField(max_length=100)),
                ('Billing_Amount', models.FloatField()),
            ],
        ),
    ]
